resolver: lts-19.32

packages:
- lowarn
- example-programs/following/versions/1.0.0
- example-programs/following/versions/2.0.0
- example-programs/following/versions/3.0.0
- example-programs/following/transformers/1.0.0-2.0.0
- example-programs/following/transformers/2.0.0-3.0.0
