name:                lowarn
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             MIT
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

extra-source-files:
- README.md

synopsis:            Practical dynamic software updating
category:            System

description:         Please see the README on GitHub at <https://github.com/jonathanjameswatson/lowarn/tree/main/core#readme>

dependencies:
- base >= 4.7 && < 5
- ghc == 9.0.2
- ghc-paths
- transformers
- unix

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -dynamic
- -shared
- -fPIC

library:
  source-dirs: src
