name:                lowarn-programs-program3
version:             0.1.0.0
github:              "jonathanjameswatson/lowarn"
license:             BSD3
author:              "Jonathan Watson"
maintainer:          "23344719+jonathanjameswatson@users.noreply.github.com"
copyright:           "2022 Jonathan Watson"

description:         Lowarn demo program 3

dependencies:
- base >= 4.7 && < 5
- lowarn
- containers
- regex-tdfa ^>= 1.3.2
- lowarn-programs-program2

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -dynamic

library:
  source-dirs: src
