name: CI
on: push
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v7
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    strategy:
      matrix:
        ghc: ["8.10.7"]
      fail-fast: true
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: ${{ runner.os }}-stack-global-
      - name: Cache .stack-work
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: ${{ runner.os }}-stack-work-
      - name: Install dependencies
        run: stack build --fast --test --only-dependencies --verbosity error
      - name: Build
        run: stack build --fast
      - name: Test
        run: stack test --fast
