name: CI
on: push
jobs:
  ormolu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mrkkrp/ormolu-action@v7
  build:
    runs-on: ubuntu-latest
    needs: ormolu
    strategy:
      matrix:
        ghc: ["9.0.2"]
      fail-fast: true
    name: GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Haskell
        id: install-haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Add Cabal programs to PATH
        run: echo "$HOME/.cabal/bin" >> $GITHUB_PATH
      - name: Install cabal-docspec
        run: |
          mkdir -p $HOME/.cabal/bin
          curl -sL https://github.com/phadej/cabal-extras/releases/download/cabal-docspec-0.0.0.20211114/cabal-docspec-0.0.0.20211114.xz > cabal-docspec.xz
          echo 'e224700d9e8c9ec7ec6bc3f542ba433cd9925a5d356676c62a9bd1f2c8be8f8a  cabal-docspec.xz' | sha256sum -c -
          xz -d < cabal-docspec.xz > $HOME/.cabal/bin/cabal-docspec
          rm -f cabal-docspec.xz
          chmod a+x $HOME/.cabal/bin/cabal-docspec
          cabal-docspec --version
      - name: Cabal freeze
        run: cabal freeze
      - name: Cache Cabal
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}"
          path: |
            ${{ steps.install-haskell.outputs.cabal-store }}
            dist-newstyle
      - name: Install dependencies
        run: cabal build all --enable-tests --only-dependencies
      - name: Build
        run: cabal build all --enable-tests
      - name: Set test suite package environment
        run: |
          echo "LOWARN_PACKAGE_ENV=$(realpath .ghc.environment*)" >> $GITHUB_ENV
      - name: Run test suite
        run: cabal test all --enable-tests --show-details=streaming
      - name: Run doctests
        run: cabal-docspec
      - name: Run Haddock
        run: cabal haddock lowarn lowarn-test lowarn-arbitrary
