name: Auto assign PRs
on:
  pull_request:
    types: [opened]
jobs:
  assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kyoya0819/auto-assignment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          users: '["jonathanjameswatson"]'
